export enum NotificationType {
  APPLICATION_SUBMITED = "APPLICATION_SUBMITED",
  APPLICATION_APPROVED = "APPLICATION_APPROVED",
  APPLICATION_REJECTED = "APPLICATION_REJECTED",
  APPLICATION_REQUIRED = "APPLICATION_REQUIRED",
  APPLICATION_CONFIRMED = "APPLICATION_CONFIRMED",
}

export enum NotificationEntityType {
  AGENT_APPLICATION = "AGENT_APPLICATION",
  AGENCY_APPLICATION = "AGENCY_APPLICATION",
}
