export enum AgentNotificationType {
  AGENT_APPLICATION_SUBMITED = "AGENT_APPLICATION_SUBMITED",
  AGENT_APPLICATION_APPROVED = "AGENT_APPLICATION_APPROVED",
  AGENT_APPLICATION_REJECTED = "AGENT_APPLICATION_REJECTED",
  AGENT_APPLICATION_REQUIRED = "AGENT_APPLICATION_REQUIRED",
  AGENT_APPLICATION_CONFIRMED = "AGENT_APPLICATION_CONFIRMED",
}

export enum AgentNotificationEntityType {
  AGENT_APPLICATION = "AGENT_APPLICATION",
  AGENT = "AGENT",
}
